import { chromium, expect } from '@playwright/test';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({channel:'msedge',headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce',acceptDownloads:true});
const page = await context.newPage();
const errors=[], requests=[], checks=[];
page.on('pageerror',e=>errors.push(e.message));
context.on('request',r=>requests.push({url:r.url(),method:r.method(),body:r.postData()}));
await mkdir('artifacts',{recursive:true});
try {
  await page.goto(process.env.AMANO_URL || 'http://127.0.0.1:5182');
  await expect(page.locator('.object-card')).toHaveCount(10);
  const search=page.getByRole('searchbox');
  await search.fill('estuche gris');
  await expect(page.locator('.card-title')).toHaveText(['Adaptador USB-C a HDMI']);
  checks.push('Recorded location found by words, before AI.');
  await search.fill('');
  await page.getByRole('button',{name:'Mis cosas',exact:true}).click();
  await expect(page.locator('.object-card')).toHaveCount(0);
  await page.getByRole('button',{name:'Añadir objeto',exact:true}).click();
  await page.getByLabel('¿Qué objeto es?').fill('Linterna de prueba');
  await page.getByLabel('¿Dónde lo guardaste?').fill('Caja centinela AMANO_PRIVATE_SYNTHETIC_8491');
  await page.getByLabel('Una pista o para qué lo usas').fill('Sirve para iluminar cuando se va la luz. Dato sintético de prueba.');
  await page.getByRole('button',{name:'Guardar objeto',exact:true}).click();
  await expect(page.locator('.object-card')).toHaveCount(1);
  await page.reload();
  await expect(page.locator('.card-title')).toHaveText(['Linterna de prueba']);
  await page.getByRole('button',{name:'Editar Linterna de prueba',exact:true}).click();
  await page.getByLabel('¿Dónde lo guardaste?').fill('Segunda caja AMANO_PRIVATE_SYNTHETIC_8491');
  await page.getByRole('button',{name:'Guardar objeto',exact:true}).click();
  await expect(page.locator('.card-place')).toContainText('Segunda caja');
  await page.getByRole('button',{name:'Añadir a favoritos: Linterna de prueba',exact:true}).click();
  await expect(page.getByRole('button',{name:'Quitar de favoritos: Linterna de prueba',exact:true})).toHaveAttribute('aria-pressed','true');
  checks.push('Personal add/edit/favorite survive local persistence; isolated from fictional demo.');
  await page.getByRole('button',{name:'Copias de seguridad',exact:true}).last().click();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:/Descargar mi colección/}).click();
  const download=await downloadPromise;
  await download.saveAs('artifacts/synthetic-backup.json');
  const backup=JSON.parse(await readFile('artifacts/synthetic-backup.json','utf8'));
  assert.equal(backup.items[0].title,'Linterna de prueba');
  await page.getByRole('button',{name:'Cerrar diálogo',exact:true}).click();
  await page.getByRole('button',{name:'Linterna de prueba',exact:true}).click();
  await page.getByRole('button',{name:'Eliminar Linterna de prueba',exact:true}).click();
  await page.getByRole('button',{name:'Conservar',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Linterna de prueba',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Eliminar Linterna de prueba',exact:true}).click();
  await page.getByRole('button',{name:'Sí, borrar ficha',exact:true}).click();
  await expect(page.locator('.object-card')).toHaveCount(0);
  await page.getByRole('button',{name:'Copias de seguridad',exact:true}).last().click();
  await page.getByLabel('Archivo de copia de seguridad').setInputFiles('artifacts/synthetic-backup.json');
  await expect(page.getByRole('heading',{name:'Tu copia está lista.'})).toBeVisible();
  await page.getByRole('button',{name:'Reemplazar y restaurar',exact:true}).click();
  await expect(page.locator('.object-card')).toHaveCount(1);
  checks.push('Backup exported, delete canceled/confirmed, validated restore explicitly confirmed.');
  await page.getByRole('button',{name:'Explorar demo',exact:true}).click();
  await expect(page.locator('.object-card')).toHaveCount(10);
  await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
  for(const width of [375,390,768]) {
    await page.setViewportSize({width,height:900});
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`overflow at ${width}`);
    await page.screenshot({path:`artifacts/viewport-${width}.png`,fullPage:true});
  }
  await page.setViewportSize({width:1440,height:1050});
  console.log('CRUD, backup and viewport checks passed. Activating real browser model.');
  const start=Date.now();
  await page.getByRole('button',{name:'Activar',exact:true}).click();
  await expect(page.locator('.semantic-copy strong')).toHaveText('También entiende cómo lo describes',{timeout:180000});
  const loadMs=Date.now()-start;
  await search.fill('quiero mostrar la pantalla del computador en el televisor');
  await expect(page.locator('.results-explanation')).toContainText('sugerencias por significado',{timeout:30000});
  const semanticTitles=await page.locator('.card-title').allTextContents();
  assert(semanticTitles.includes('Adaptador USB-C a HDMI'),'semantic indirect query failed');
  await page.locator('.card-title').filter({hasText:'Adaptador USB-C a HDMI'}).click();
  await expect(page.locator('.location-note strong')).toHaveText('Cajón superior del escritorio · estuche gris');
  await page.screenshot({path:'artifacts/semantic-result.png'});
  await page.getByRole('button',{name:'Cerrar diálogo',exact:true}).click();
  await search.fill('estuche gris');
  await expect(page.locator('.results-explanation')).toContainText('sugerencias por significado',{timeout:30000});
  await expect(page.locator('.card-title').filter({hasText:'Adaptador USB-C a HDMI'})).toBeVisible();
  await search.fill('pasaporte AMANO_PRIVATE_SYNTHETIC_8491');
  await expect(page.locator('.results-explanation')).toContainText('sugerencias por significado',{timeout:30000});
  await expect(page.locator('.object-card')).toHaveCount(0);
  await search.fill('lluvia'); await search.fill('');
  await expect(page.locator('.semantic-copy strong')).toHaveText('También entiende cómo lo describes',{timeout:30000});
  await context.setOffline(true);
  await search.fill('arreglar un botón de mi camisa');
  await expect(page.locator('.results-explanation')).toContainText('sugerencias por significado',{timeout:30000});
  assert((await page.locator('.card-title').allTextContents()).includes('Kit de costura'));
  await context.setOffline(false);
  checks.push('Real ONNX WASM browser inference: indirect Spanish query, exact location retained, absent query, clear in-flight query, offline inference in already-loaded session.');
  assert(!requests.some(r=>`${r.url} ${r.body}`.includes('AMANO_PRIVATE_SYNTHETIC_8491')),'sentinel left device');
  assert.equal(errors.length,0,errors.join('\n'));
  await writeFile('artifacts/browser-check.json',JSON.stringify({time:new Date().toISOString(),status:'passed',browser:'Headless Edge isolated context',loadMs,semanticTitles,checks,errors,requests:requests.map(({url,method})=>({url:new URL(url).origin+new URL(url).pathname,method})),limits:['Synthetic data only; no household or physical mobile user test.','Offline tested in already-loaded session, not offline page reload.','Model similarity is not a probability; false matches remain possible.']},null,2));
  console.log('ALL BROWSER CHECKS PASSED',JSON.stringify({loadMs,semanticTitles}));
} catch(error) {
  await page.screenshot({path:'artifacts/check-failure.png',fullPage:true}).catch(()=>{});
  await writeFile('artifacts/browser-check-failure.json',JSON.stringify({error:String(error),errors,checks,requests:requests.map(({url,method})=>({url:new URL(url).origin+new URL(url).pathname,method}))},null,2));
  throw error;
} finally { await browser.close(); }
